### ISSUE TITLE
I am the owner of server but it says no permission or command is disabled

### ISSUE THREAD

**Issue by ghost** [MonikaDiscord/Monika#12]
I have just added monika to server but when i try $!insult command it says : 
> Either you don't have permissions to do this or this command is disabled.
ı have tried to give all the permission to myself but bno results and i didnt disable anything, there is no command to enable it

**Comment by KnifuWaifu** [comment]
You have to upvote the bot I think in order for that command

**Comment by ghost** [comment]
so it was just matter of upvoting the bot it is not a real issue but you should warn peoples in command list to vote the bot to use those commands

**Comment by KnifuWaifu** [comment]
Look at the command list carefully, please. It tells you about which commands you need to upvote or be a patron to.
