### ISSUE TITLE
$!duck raises Exception

### ISSUE THREAD

**Issue by Samuraiwarm** [MonikaDiscord/Monika#25]
Here is the error message when sending command `$!duck`.

```
Command` raised an exception: ClientConnectorError: Cannot connect to host api.random-d.uk:443 ssl:None [Name or service not known]
```

Thank you!

**Comment by namrednels** [comment]
They there, thanks for the report. Random-d.uk changed their API. I have created a PR to fix this.

**Comment by tangalbert919** [comment]
This issue has been resolved. Closing.
